"""initial_migration

Revision ID: 333908f95097
Revises: 
Create Date: 2026-06-04 16:59:44.884180
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333908f95097'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('flag_url', sa.String(length=500), nullable=True),
    sa.Column('flag_emoji', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('api_football_id', name=op.f('uq_leagues_api_football_id'))
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('favorite_teams', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_seasons_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_index(op.f('ix_seasons_league_id'), 'seasons', ['league_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_api_football_id'), 'teams', ['api_football_id'], unique=True)
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_table('head_to_head',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('team1_wins', sa.Integer(), nullable=False),
    sa.Column('team2_wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('total_goals', sa.Integer(), nullable=False),
    sa.Column('last_matches', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], name=op.f('fk_head_to_head_team1_id_teams')),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], name=op.f('fk_head_to_head_team2_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_head_to_head'))
    )
    op.create_index(op.f('ix_head_to_head_team1_id'), 'head_to_head', ['team1_id'], unique=False)
    op.create_index(op.f('ix_head_to_head_team2_id'), 'head_to_head', ['team2_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_ht_score', sa.Integer(), nullable=True),
    sa.Column('away_ht_score', sa.Integer(), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('referee', sa.String(length=200), nullable=True),
    sa.Column('is_g3_vs_z3', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_matches_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_api_football_id'), 'matches', ['api_football_id'], unique=True)
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_is_g3_vs_z3'), 'matches', ['is_g3_vs_z3'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('home_played', sa.Integer(), nullable=False),
    sa.Column('home_won', sa.Integer(), nullable=False),
    sa.Column('home_drawn', sa.Integer(), nullable=False),
    sa.Column('home_lost', sa.Integer(), nullable=False),
    sa.Column('home_goals_for', sa.Integer(), nullable=False),
    sa.Column('home_goals_against', sa.Integer(), nullable=False),
    sa.Column('away_played', sa.Integer(), nullable=False),
    sa.Column('away_won', sa.Integer(), nullable=False),
    sa.Column('away_drawn', sa.Integer(), nullable=False),
    sa.Column('away_lost', sa.Integer(), nullable=False),
    sa.Column('away_goals_for', sa.Integer(), nullable=False),
    sa.Column('away_goals_against', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_standings_season_id_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_standings_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings')),
    sa.UniqueConstraint('season_id', 'team_id', name='uq_standing_season_team')
    )
    op.create_index(op.f('ix_standings_season_id'), 'standings', ['season_id'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('analysis_sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_ai_analyses_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_match_id'), 'ai_analyses', ['match_id'], unique=True)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_notification_logs_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.create_index(op.f('ix_notification_logs_match_id'), 'notification_logs', ['match_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('over_2_5_prob', sa.Float(), nullable=True),
    sa.Column('btts_prob', sa.Float(), nullable=True),
    sa.Column('model_inputs', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_notification_logs_match_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_ai_analyses_match_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_season_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_is_g3_vs_z3'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_api_football_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_head_to_head_team2_id'), table_name='head_to_head')
    op.drop_index(op.f('ix_head_to_head_team1_id'), table_name='head_to_head')
    op.drop_table('head_to_head')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_api_football_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_league_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
